fix: true
parallel: true
format: progress

plugins:
  - standard-performance
  - standard-rspec

extend_config:
  - .rubocop/rspec.yml
  - .rubocop/custom.yml

ignore:
  - bin/**/*
  - db/*
  - vendor/**/*
  - tmp/**/*
  - log/**/*
  - storage/**/*
  - coverage/**/*
  - uploads/**/*
  - .git/**/*
  - usr/**/*
  - "spec/**/*":
    - RSpec/SpecFilePathFormat
    - RSpec/HooksBeforeExamples
  - "**/*":
    - Style/FrozenStringLiteralComment
    - Lint/UselessAssignment
